version: "3.7"
services:
  pairup:
    build:
      context: ${HOME}/${REPOS}/${REPO}
      dockerfile: docker/${APP}/Dockerfile
    image: ${APP}:0.0.1
    command:
      - "jupyter"
      - "lab"
      - "--allow-root" # Needed to run as root user
      - "--ip=0.0.0.0" # Needed when running inside a Docker container
      - "--port=${JUPYTERLAB_PORT}"
      - "--no-browser"
      - "--LabApp.token=''" # Turn off security feature
    # 'init: true' indicates Docker will handle child process reaping.
    # This is critical for Jupyter to run correctly inside Docker.
    init: true
    ports:
      - "${JUPYTERLAB_PORT}:${JUPYTERLAB_PORT}"
    environment:
      - PYTHONPATH=${PYTHON_SITE_PACKAGES}
    volumes:
      - ${HOME}/${REPOS}/${REPO}/pairup/:${PYTHON_SITE_PACKAGES}/pairup/
      - ${HOME}/${VOLUMES}/notebooks/:/${APP}/notebooks/
      - ${HOME}/${VOLUMES}/configuration/.jupyter/:/root/.jupyter/
